### ISSUE TITLE
作者你好 用了汉化后出现手柄图标显示不正常希望能够修复

### ISSUE THREAD

**Issue by Morolk** [BDO-CnHope/bdocn_client#11]
RT,我是手柄用户，不管是打了繁体还是简体的，招式UI那边都是不显现正确的图标，很大可能性是字体的问题~切换到英文的又正常了，希望能够修复！

**Comment by Naunter** [comment]
关于这个问题之前也有人报告了。我猜测的是手柄的文件应该是封装在PAC里，里面包含了它自己专门的字体，但被汉化所需要的字体顶替了，所以才显示不正常。

如果是字体造成的原因，我给出个临时的解决办法就是自己替换字体，看看结果是不是由于汉化的字体导致的。因为要顾及多个服区和语言的兼容性，我选择使用的字体为[Source Han Sans (思源黑体)](https://github.com/adobe-fonts/source-han-sans), 是一种能兼容简体中文、繁体中文、韩文、日语和英语的字体。

因为我近来确实是没什么时间能去对黑沙的汉化进行大的测试和修改。还请告知你替换字体后的测试结果，谢谢!
   
**替换字体的步骤:**
1. 打开黑沙的游戏根目录
2. 找到目录下的`prestringtable`文件夹
    - 如果没有，请自行新建一个
3. 在`prestringtable`文件夹里，找到`font`的文件夹
    - 如果没有，请自行新建一个
4. 在`font`下，放入你要替换的字体文件，然后将字体文件重命名为`pearl.ttf`
   - 完整的字体路径为`...\黑沙的游戏根目录\prestringtable\font\pearl.ttf`
6. 使用汉化工具进行汉化时，在**第3步**记得勾选`不要覆盖现有的汉化字体`。不然汉化程序会把你自己替换的字体给覆盖了。
![image](https://user-images.githubusercontent.com/17890335/162590154-bab27881-ee41-4112-b94a-da89ac6d2af9.png)

**Comment by Morolk** [comment]
作者你好，我今天试过了~替换字体后依旧是不显示~估计是其它的问题~

**Comment by Naunter** [comment]
那这个问题暂时没有很好的解决办法了，只能暂时搁置等以后我有时间再研究，或者搜索下网上有没有其它的解决方案。

**Comment by Morolk** [comment]
好的！那幸苦作者了，期待有空帮忙解决

**Comment by Naunter** [comment]
因为各种原因，这个问题一直被遗留没有时间去修复。。。

而且不好意思啊，这个汉化工具项目已经暂停更新和维护了。如需要更好的体验，请在网上另寻其它的汉化工具使用吧。

感谢你的使用和支持。
