### ISSUE TITLE
请问4k显示器在缩放大于100时字体变得模糊该怎么办

### ISSUE THREAD

**Issue by Aoldbald** [BDO-CnHope/bdocn_client#12]
如果用100缩放，字体在4k显示器下太小

**Comment by Naunter** [comment]
额，这个我是真没办法，因为这是黑沙游戏程序本身的问题，而这汉化工具说白了就只是个语言文件替换工具而已。

至于解决方法，这个你只能向黑沙官方去提议让他们改进了，让他们去优化和适配大屏幕/4K的显示比例和字体显示。
或者你也可以自己网上搜索下类似的问题，看看有没有解决方法。

**Comment by Aoldbald** [comment]
好的，请问可以替换汉化的字体吗？我试试其他字体也许会改善模糊的问题。

**Comment by Naunter** [comment]
可以替换字体。

1. 把字体文件放到`黑沙游戏的文件目录/prestringtable/font/`下，把字体文件重命名为`pearl.ttf`
2. 记得勾选`不覆盖字体`的选项。
![image](https://user-images.githubusercontent.com/17890335/235050414-b8b5f3a2-2950-4e58-a037-05e461ec800f.png)
3. 如果你想恢复原来的汉化字体，就`不勾选`, 然后汉化工具会重新下载回原汉化用的字体。

**Comment by Aoldbald** [comment]
感谢!

**Comment by Naunter** [comment]
这个汉化工具项目已经暂停更新和维护了。如需要更好的体验，请在网上另寻其它的汉化工具使用吧。

感谢你的使用和支持。
