### ISSUE TITLE
替换按钮不高亮

### ISSUE THREAD

**Issue by zrongqing** [BDO-CnHope/bdocn_client#13]
看了一下代码. 替换按钮可点击状态是通过 BlackDesertPatcher32.pae 进程来判断, 但是通过steam启动的启动器, 不是这个进程..

下面是操作步骤
![PixPin_2024-03-21_21-14-12](https://github.com/BDO-CnHope/bdocn_client/assets/46354863/66b76240-ee40-4aef-90d8-d1033d9ae7c7)

**Comment by zrongqing** [comment]
MD 是东南亚服...

**Comment by Naunter** [comment]
你上面使用的汉化工具不是我们这个项目开发的...
