### ISSUE TITLE
汉化不成功

### ISSUE THREAD

**Issue by LeonCrashCode** [BDO-CnHope/bdocn_client#3]
汉化后，运行游戏，文字无法显示。英文和中文都不显示。游戏是在steam下载欧服，系统是window10

**Comment by Naunter** [comment]
> 
> 
> 汉化后，运行游戏，文字无法显示。英文和中文都不显示。游戏是在steam下载欧服，系统是window10

字体没安装好？

**Comment by Naunter** [comment]
> 
> 
> 汉化后，运行游戏，文字无法显示。英文和中文都不显示。游戏是在steam下载欧服，系统是window10

能给个截图看看是什么没显示，我账号没转移上不了黑沙…

**Comment by Rokeer** [comment]
我通过直接覆盖文件的方式安装的汉化。如果先安装汉化，再启动客户端，languagedata_en.loc文件会被重新下载并覆盖。于是我先打开了启动器，再手动覆盖这个文件。游戏打开后，所有应该显示中文的地方，都没有显示内容。我也是steam下的美服。

![image](https://user-images.githubusercontent.com/1813573/110799677-6d207800-8249-11eb-87d1-dd05b034d6ac.png)
![image](https://user-images.githubusercontent.com/1813573/110799713-7578b300-8249-11eb-820a-6448565bb847.png)

我把ads和prestringtable两个文件夹放到了游戏的根目录，以防万一，我还手动安装了prestringtable文件夹内的字体到我的系统里。

**Comment by Rokeer** [comment]
用客户端安装，效果也是一样的。

另外，还发现了一个有趣的现象，就是我通过先打开启动器，再安装汉化的方式进游戏。虽然游戏内的文字都是不显示了。但是程序的进程名字从英文变成了中文的黑色沙漠。

**Comment by Rokeer** [comment]
我使用了客户端提供的恢复英文功能。但是打开启动器之后，依旧更新了languagedata_en.loc文件，所以会不会是文件版本的问题？

**Comment by Rokeer** [comment]
大致找到问题了
1. steam版本确实在每次打开启动器的时候会恢复所有文件，所以需要在启动器更新完之后再覆盖汉化文件。
2. C:\Users\xxxxx\Documents\Black Desert\GameOption.txt文件中，需要将UIFontType = 2改为1。
3. 然后汉化就可以用了

**Comment by Naunter** [comment]
> 
> 
> 大致找到问题了
> 
>     1. steam版本确实在每次打开启动器的时候会恢复所有文件，所以需要在启动器更新完之后再覆盖汉化文件。
> 
>     2. C:\Users\xxxxx\Documents\Black Desert\GameOption.txt文件中，需要将UIFontType = 2改为1。
> 
>     3. 然后汉化就可以用了

感谢提出的解决办法！我会找个时间修复这个问题的

**Comment by Naunter** [comment]
emmmm, 大致的看了下，新版本改了好多东西，要花点时间来整理下…

**Comment by Rokeer** [comment]
看了一下源码，貌似暂时还可以用，唯一需要加的功能是修改我的文档中的那个GameOption的配置文件。然后提示大家每次在打开启动器更新完毕后，重新安装汉化。

**Comment by Naunter** [comment]
@Rokeer @LeonCrashCode 已修正。如果没问题我就Close了
