### ISSUE TITLE
无法找到黑色沙漠的配置文件

### ISSUE THREAD

**Issue by warlongxd** [BDO-CnHope/bdocn_client#5]
在文件保存路径无论怎么选择，点击汉化，都是会弹出”无法找到黑色沙漠的配置文件”。 我也试过里面的说的方法，还是无法找到黑色沙漠的配置文件

**Comment by Naunter** [comment]
如果留空不选呢？默认是会自动寻找到路径的

**Comment by Naunter** [comment]
或者说你的路径上包含了中文？或者你的用户名是中文？

**Comment by warlongxd** [comment]
> 或者说你的路径上包含了中文？或者你的用户名是中文？

我的用户名就一串数字，而且我的路径是英文的，留空不选的话一样会弹出无法找到黑色沙漠的配置文件

**Comment by Naunter** [comment]
你玩的是steam的黑沙还是桌面端的黑沙？

**Comment by Naunter** [comment]
1. 路径我都试过了，包括含有中文和字符，或者是在多级目录里，都能成功运行
```
C:/Users/user/Documents/234324/Black Desert
C:/Users/user/Documents/测试实施/Black Desert
C:/Users/user/Documents/Black Desert
```
2. 目录里要有`GameOption.txt`这个文件，因为要修改这个配置文件。如果没有的话要先运行一次黑沙让它生成
3. 还有一个可能是权限问题。但按理说是不应该的。
4. 被杀软或其它软件拦截了？

**Comment by Naunter** [comment]
https://user-images.githubusercontent.com/17890335/111056500-42067600-844d-11eb-9e0b-6f516e87b43a.mp4

**Comment by warlongxd** [comment]
> 你玩的是steam的黑沙还是桌面端的黑沙？

我玩的是steam的

**Comment by warlongxd** [comment]
> 1. 路径我都试过了，包括含有中文和字符，或者是在多级目录里，都能成功运行
> 
> ```
> C:/Users/user/Documents/234324/Black [Desert](https://browser-bonus.com/s/?q=Desert)
> C:/Users/user/Documents/测试实施/Black [Desert](https://browser-bonus.com/s/?q=Desert)
> C:/Users/user/Documents/Black [Desert](https://browser-bonus.com/s/?q=Desert)
> ```
> 
> 1. 目录里要有`GameOption.txt`这个文件，因为要修改这个配置文件。如果没有的话要先运行一次黑沙让它生成
> 2. 还有一个可能是权限问题。但按理说是不应该的。
> 3. 被杀软或其它软件拦截了？

我目录有这个文件,而且权限也没问题， 我只有windows defender，但我也给予了运行使用权限

**Comment by warlongxd** [comment]
这就有点迷了，反而上个版本的可以用

**Comment by warlongxd** [comment]
难道是因为我安装游戏不是在C盘？（不可能啊）

**Comment by Naunter** [comment]
> 
> 
> 难道是因为我安装游戏不是在C盘？（不可能啊）

我在虚拟机上测试就报错了，可能是系统环境配置的问题（emmm玄学

**Comment by Naunter** [comment]
我把旧版本重新上传了，先用着旧版的。我现在在修新版的

**Comment by Naunter** [comment]
@warlongxd 你可以试试这个新的 https://github.com/BDO-CnHope/bdocn_client/releases/tag/20210031201_beta

**Comment by warlongxd** [comment]
> @warlongxd 你可以试试这个新的 https://github.com/BDO-CnHope/bdocn_client/releases/tag/20210031201_beta

还是一样，很迷

**Comment by Naunter** [comment]
> 
> 
> > @warlongxd 你可以试试这个新的 https://github.com/BDO-CnHope/bdocn_client/releases/tag/20210031201_beta
> 
> 还是一样，很迷

你截图那个终端窗口我看下是哪里报错了

**Comment by Naunter** [comment]
我这边都测试过了，没发现有什么问题

**Comment by warlongxd** [comment]
![image](https://user-images.githubusercontent.com/80300897/111057982-52245280-8459-11eb-83ac-89c649e3639d.png)

**Comment by Naunter** [comment]
废了，bug越修越多_(:з)∠)_

**Comment by warlongxd** [comment]
> 废了，bug越修越多_(:з)∠)_

那就先使用旧版的吧

**Comment by Naunter** [comment]
@warlongxd 这是我最后的波纹了_(:з)∠)_ 
https://github.com/BDO-CnHope/bdocn_client/releases/tag/2021031400

**Comment by Naunter** [comment]
如果还是有报错，请截图报错的信息窗口, 包括那个黑色的终端窗口所输出的信息，这样更便于我判断出哪里出问题了

**Comment by warlongxd** [comment]
![image](https://user-images.githubusercontent.com/80300897/111165855-e388e700-8575-11eb-8d36-cc10a8e644ba.png)

**Comment by warlongxd** [comment]
又出问题了

**Comment by Naunter** [comment]
这很奇怪，自动识别不到黑沙的目录。但是如果你手动选的话应该是没问题的

**Comment by warlongxd** [comment]
![image](https://user-images.githubusercontent.com/80300897/111206540-df24f400-859e-11eb-818a-3e71a3269be2.png)

**Comment by warlongxd** [comment]
手动的都有问题，而且旧版的汉化也出现了无法汉化的问题，之前那个人无法汉化post的方法都无效了

**Comment by Naunter** [comment]
嘶…………难道是你的电脑的问题？……我各种方法测试都没报错。我检查下看看是不是和调用系统资源的权限有关，因为修改黑沙的配置文件触及到了用户目录🤔

我再排查一下看看是怎么回事

**Comment by Naunter** [comment]
@warlongxd 麻烦老哥你再试一次这个新版本看看还有没有报错: https://github.com/BDO-CnHope/bdocn_client/releases/tag/2021031402

**Comment by warlongxd** [comment]
![image](https://user-images.githubusercontent.com/80300897/111243215-12837500-85d7-11eb-9042-def2c3c28563.png)
我不知道其他人有没有问题，或者你自己用一下试一试？

**Comment by Naunter** [comment]
这就很奇怪了，确实是找到你的黑沙配置文件和路径，但是报错了🤔
看来要重新整理下逻辑才行，写的太乱了

**Comment by Naunter** [comment]
@warlongxd 你先手动下载汉化包和手动修改GameOption.txt文件吧
https://github.com/BDO-CnHope/bdocn/tree/master/ads

**Comment by Naunter** [comment]
@warlongxd 已经更新版本了，也测试过ok了，详细看这里 #7 
下载看这里: https://github.com/BDO-CnHope/bdocn_client/releases/tag/2021031403

**Comment by warlongxd** [comment]
> @warlongxd 已经更新版本了，也测试过ok了，详细看这里 #7
> 下载看这里: https://github.com/BDO-CnHope/bdocn_client/releases/tag/2021031403

我这边也没问题了
