### ISSUE TITLE
旧的客户端也出现错误

### ISSUE THREAD

**Issue by warlongxd** [BDO-CnHope/bdocn_client#6]
早上还好好的, 结果晚上一开汉化直接操作错误，请重试...code: 2

**Comment by Naunter** [comment]
> 
> 
> 早上还好好的, 结果晚上一开汉化直接操作错误，请重试...code: 2

这个没事，不是客户端问题，是服务器出问题了导致下载不了文件。 已经在修了_(:з)∠)_

**Comment by warlongxd** [comment]
在服务器出现问题之前，为什么突然字也变成了框框，也都是晚上出现的问题

**Comment by Naunter** [comment]
通常要不就是啥事都没有，但如果一个出了问题就各种冒出来，我也不知道为啥……所以我通常看到服务都能跑的话我基本是不会去碰的…😂

**Comment by Naunter** [comment]
@warlongxd 服务器修好了，应该不会出现error code 2了
