### ISSUE TITLE
更新版本到 2021071000

### ISSUE THREAD

**Issue by Naunter** [BDO-CnHope/bdocn_client#7]
- **如发现问题请开新issue**。或先**自行排除汉化问题**
  - [汉化问题排除步骤](https://github.com/BDO-CnHope/bdocn_client/issues/10)
  - [点我新建一个issue](https://github.com/BDO-CnHope/bdocn_client/issues/new/choose) 

- 请在提交的issus里包含报错的截图和终端窗口输出的日志(黑色的终端窗口)。
   - 或者将终端窗口输出的日志全部复制到issue里。

- 本汉化工具暂时只支持以下语言/服区的黑沙: 
   - 英语，俄语，葡萄牙语，繁体中文，法语 

- [点击下载汉化工具(v3.2021071000)](https://github.com/BDO-CnHope/bdocn_client/releases/download/v3.2021071000/bdocn_client_v3.2021071000.exe)

-----
#### 版本更新 v3.202171000
- 版本: v3.202171000
- [汉化工具使用演示](https://cnhope.onehoi.com/bdocn)

#### 版本更新 v3.2021052501
- 版本: v3.2021052501
- 添加了对俄服(俄语)，欧美服(法语)的支持
  - 但未进行过实际的游戏测试。如果成功请在下面视频评论里给我个回复。
  - [汉化工具演示视频](https://www.bilibili.com/video/BV1yf4y1s75B)

#### 版本更新 v3.2021052500
- 版本: v3.2021052500
- 做了一些小优化，加快了再次汉化的速度
- 修复了一些小问题
   - #8  
- 添加支持黑沙其他服的汉化选项。
    - 暂时只添加了台服。因为之前有人提议台服繁体换成简体
    - 大洋服(葡萄牙语), 日服(日语)
    - 但大洋服和日服我并未实际做过测试，请有测试过的可以私信我或者开个issue说一声, 谢谢。

#### 版本更新 2021031404
- 版本: 2021031404
- 修复了汉化文字显示问题 [#3](https://github.com/BDO-CnHope/bdocn_client/issues/3)
- 更新了英语文件的链接
- 修正了一些其它的错误和问题

#### 有待测试的功能
- 允许汉化工具启动黑沙(现在只支持Steam启动)
- 允许汉化工具直接执行汉化
  - 前提是第一次汉化成功后，第二次再运行汉化时就不用手动选择目录，可以直接执行汉化了
 
#### 已知但还未解决的问题(有时间再搞，或者等大佬们提出解决办法，先咕了)：
  - 因为新版本的黑沙调用了新的启动器，导致每次启动黑沙时，启动器都会自动检查游戏文件并修复/更新不匹配的文件，导致已汉化了的语言包每次都会被启动器替换。
  - 所以暂行的解决办法就是先运行黑沙的启动器，然后等启动器扫描和更新完后，再执行汉化。

#### 参考
- 黑沙客户端自动恢复汉化文字的解决办法，感谢Rokeer提出的办法:
https://github.com/BDO-CnHope/bdocn_client/issues/3#issuecomment-796784987

**Comment by Vdc-K** [comment]
replace_text.py >>> def change_ui_font(path)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "replace_text.py", line 19, in change_ui_font
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "threading.py", line 892, in run
  File "ui4.py", line 345, in start_button
  File "replace_text.py", line 19, in change_ui_font
OSError: [Errno 9] Bad file descriptor

**Comment by Naunter** [comment]
> 
> 
> replace_text.py >>> def change_ui_font(path)
> Exception in thread Thread-2:
> Traceback (most recent call last):
> File "replace_text.py", line 19, in change_ui_font
> OSError: [Errno 9] Bad file descriptor
> 
> During handling of the above exception, another exception occurred:
> 
> OSError: [Errno 9] Bad file descriptor
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "threading.py", line 954, in _bootstrap_inner
> File "threading.py", line 892, in run
> File "ui4.py", line 345, in start_button
> File "replace_text.py", line 19, in change_ui_font
> OSError: [Errno 9] Bad file descriptor

请不要再这个issue里回复。我已经把你的issue移到这里了 #8, 请使用这个新的issue。
请详细描述你的问题。你是自己进行编译所以报错了？
