### ISSUE TITLE
为什么下载了新的版本还是提示更新版本呢

### ISSUE THREAD

**Issue by Gaerliya** [BDO-CnHope/bdocn_client#9]

**Comment by Naunter** [comment]
可能是网路或者服务器的问题，但不影响使用啦。

最新版本的编号是`v3.2021052501`, 可以检查看你现在的汉化工具版本是否为最新的版本号。

最新版就添加了个`俄语`和`法语`的汉化，如果不用这两个的不更新也没关系。

**Comment by Naunter** [comment]
close
